### ISSUE TITLE
tig

### ISSUE THREAD

**Issue by txdv** [bleroy/midnightgit#2]
How would it be different compared to tig?

**Comment by bleroy** [comment]
That's a great question that I'd love to see other people's answer. Tig is great, and it exists today. Let's share what our expectations are, and how we'd like this to do better. I'll start.

1. Like in Midnight Commander, the native OS shell should be seamlessly integrated. The app is something that lives on top of, and enriches your experience of driving git from the command-line.
2. Navigation and discovery of the app's features should be simple. You should never need a help screen. I like MC's function key bar at the bottom, and its menu bar on top. Key mappings should not conflict with shell operation (see 1.)
3. No need to have Cygwin or build from source on Windows. The only dependency should be git.exe on the path.
4. It's a fun thing to build. I want to. :D

**Comment by pmiossec** [comment]
3. is solved as tig is now by default in the last versions of git for Windows ;-)

4. couldn't be solved by any other tools, so, have fun!

**Comment by bleroy** [comment]
3. It is? Nice!

**Comment by pmiossec** [comment]
Yep ;-)

**Comment by schani** [comment]
One of the main reasons I rarely use Git UIs is that I don't trust them, beyond staging and committing (especially if they rename Git's operations, like the GitHub client does).  I would never fetch, or push in a Git UI, never mind rebase.  In the shell I always know what I get.

Having said that, I really like the idea of having a shell with a built-in Git HUD(?).  I use `tig` a lot, mainly for browsing history, and sometimes for staging, and having it always on would be great.  Things that would be nice:

1. If you run a `git` command in the shell, the output is automatically shown in the HUD, and the shell is back again.  I.e. running `git log` should show the log.  Sure, it'll have a hotkey for that, which should do the same thing, but maybe I'll filter the log, or do something else nonstandard.

2. It should not have any state other than the information of what you're looking at.  For example, it shouldn't try to keep track of whether I'm rebasing independent of Git's state, because Git's state and mg's state are bound to go out of sync, especially if I do stuff on the command line.

2. A specialized editor for interactive rebase files, for example, that lets me set commits to "squash" with one key press, or move them around.

**Comment by bleroy** [comment]
Just to clarify, for your 1., @schani do you mean that when you use the shell to type a command, the HUD should understand it and switch to the corresponding view if there's one? Can you give more details about what you'd expect to happen, end-to-end?

Your 3. happens to be one of the primary scenarios I had in mind, where I think mg could make a difference and make the experience better. On the same page here.

**Comment by schani** [comment]
@bleroy One method for doing this would be to use Git's `core.pager` setting.  I have that set to `tig`, for example, so whenever I run `git log`, tig comes up, and it understands what it's looking at.  So for mg you'd set that to `mg-client`, which connects to the mg you're running and pipes the data through.

If mg needs to know more about what's going on, it might have to parse the command line, or maybe supply its own `git` wrapper, but both of those are somewhat brittle, so I'd want to go with the pager as long as is feasible.
